### ISSUE TITLE
Refactor build scripts on build/exe

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-dmeservices/user-sync.py#2]
The PyInstaller project will need at least one additional build script in the future (resource bundler).  To keep things organized, we should move most of our build scripts to one central directory.  The Makefile, setup.py and PyInstaller spec file can remain in the root directory.

* create `.build/` directory on repo root
* move `.travis/` inside `.build/`
* move `.appveyor/` inside `.build/`
* update CI config scripts to reflect new paths for CI build scripts
* the icon for the EXE build can live in `.build/`
* the build directory will be the future home of the resource bundler script

**Comment by vossen-adobe** [comment]
Do you want to include the .pyinstaller folder here as well? (Or do we even want a separate folder for the bat and sh, since these are basically one liners that could go into a script)

**Comment by adorton-adobe** [comment]
I don't think we'll need it at this point.  If we use the spec file to build the executable (see #3) then we won't need the platform-specific build files.  And the icon file can live in `.build/`.
