### ISSUE TITLE
Create PyInstaller spec on build/exe

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-dmeservices/user-sync.py#3]
The spec file generated by PyInstaller should be the primary build script for PyInstaller builds.  This is the most common way to use PyInstaller that I've observed in other projects.  When the project is initially built from the application file, the spec file is generated and becomes the primary build script.

This will come in handy when we need to add resource bundling and potentially platform-specific build configuration in the future.

Let's call the file `user-sync.spec` and commit it to the branch root.

**Comment by adorton-adobe** [comment]
I should also note that the way to build with a spec is simple.  Since the spec file encapsulates all of the parameters passed to `pyinstaller` in the initial build, only the spec needs to be passed to `pyinstaller`:

```sh
$ pyinstaller user-sync.spec
```

This will be run from the Makefile in the `exe` target.

**Comment by vossen-adobe** [comment]
Edit: actually I think I've got the right approach now. Disregard previous comment.
